### ISSUE TITLE
ec2_ephemeralswap is broken

### ISSUE THREAD

**Issue by cperciva** [cperciva/ec2-scripts#1]
This script is broken in two ways:

1. The "don't try to create more swap than the kernel knows how to manage" code looks at SWAPMETA from `vmstat -z`, which no longer exists in FreeBSD 11+.

2. The script assumes that everything ephemeral is a Xen disk; we should handle nvme disks too.

Distinguishing between "nvme" ephemeral and non-ephemeral disks should be done by looking at their "model name".

**Comment by metalefty** [comment]
Hi, I'm meta@FreeBSD.org.
Just for a record: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=234686

**Comment by cperciva** [comment]
Fixed in a9c24be73ef62d621f013575a5e891eb3a81dac5.
